lang: pt

project:
  output-dir: docs/pt

website:
  navbar:
    left:
      - href: /index.html
        text: "**PT**"
      - href: ../en/index.html
        text: EN  
      - href: ../index.html
        text: ES      
      - text: "Página inicial"
        href: /index.html
      - text: "Novidades"
        href: blog/pt/index.html                 
      
        