lang: en

project:
  output-dir: docs/en

website:
  navbar:
    left:
      - href: ../pt/index.html
        text: "PT"
      - href: ./index.html
        text: "**EN**"  
      - href: ../index.html
        text: "ES"    
    right:
      - text: "Home"
        href: /index.qmd