project:
  type: website
  preview: 
    port: 4200  

website:
  title: "LatinR 2023"
  sidebar: false
  navbar:
    pinned: false
    logo: "images/logo.png"
    logo-alt: "Latin-R logo"
    title: false
    background: "#ffffff"
    foreground: "#737373"
  page-footer: 
#    left: "Proudly supported by R Consortium"
    center: "Copyright © 2023, LatinR Team" 
    right: 
      - icon: envelope
        href: mailto:latinr.conf@gmail.com   
      - icon: twitter 
        href: https://twitter.com/LatinR_Conf        
      - icon: linkedin
        href: https://www.linkedin.com/company/latinrconf/
      - icon: slack
        href: https://latin-r.slack.com/join/shared_invite/enQtNDA3MjM3MTQwOTM1LTg3ZWMyNWU3MGI2MGM5YzU0MGU4NWE5NjYwMjBhMGZmYTQzYTA0ODZlOTE1NDc0YzIwM2NhYTJiNDQyZjMzZjc


      
profile:
  default: es
  group: 
    - [en, es, pt]

format:
  html:
    theme: styles.scss
    toc: false
    page-layout: custom

editor: visual

