project:
  type: website
  preview: 
    port: 4200  

website:
  title: "LatinR 2023"
      
profile:
  default: es
  group: 
    - [en, es, pt]      

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

