lang: es

project:
  output-dir: docs

website:
  navbar:
    left:
      - href: ./pt/index.html
        text: "PT"
      - href: ./en/index.html
        text: EN  
      - href: /index.html
        text: "**ES**"    
      - text: "Principal"
        href: /index.qmd